


obj-$(CONFIG_OPTRANN_FE_ETH) += optrann_fe.o optrann_app.o
obj-$(CONFIG_ONU_FE_ETH)	+= onu_fe.o atheros_old.o
obj-$(CONFIG_ONU_FE_VOIP_F13_ETH)	+= onu_voip_fe.o
obj-$(CONFIG_ONU_FE_VOIP_F23_ETH)	+= onu_voip_fe.o
obj-$(CONFIG_ONU_FE_VOIP_F33_ETH)	+= onu_voip_fe_f33.o
obj-$(CONFIG_ONU_FE_UT_F23_ETH)	+= onu_voip_fe_ut.o
obj-$(CONFIG_ONU_FE_ETH_D2)	+= onu_fe_d2.o atheros_old.o
obj-$(CONFIG_ONU_FE_RESPIN_F13_ETH)	+= onu_voip_fe.o
obj-$(CONFIG_ONU_FE_RESPIN_F23_ETH)	+= onu_voip_fe.o
obj-$(CONFIG_ONU_FE_RESPIN_C13_ETH)	+= onu_voip_fe.o
obj-$(CONFIG_ONU_FE_RESPIN_RF400_ETH) += onu_respin_fe_rf400.o
