#include <configs/opipmux.h>
#ifdef INCLUDE_UART_TEST
void testuart()
{
	unsigned int i;
	puts("------------------begin uart test----------------- \n");
	puts("------------------begin uart test----------------- \n");
	puts("------------------begin uart test----------------- \n");
	puts("------------------begin uart test----------------- \n");
	puts("------------------begin uart test----------------- \n");
	puts("------------------begin uart test----------------- \n");
				
	puts("#(C) Copyright 2001 - 2005                                                                 \n");  
	puts("#Wolfgang Denk, DENX Software Engineering, wd@denx.de.                                     \n");
	*(char *)0x80000000='a';

	puts("#                                                                                           \n");
	puts("#See file CREDITS for list of people who contributed to this                               \n");
	puts("#project.                                                                                  \n");
	*(char *)0x80000000='a';
	puts("#                                                                                           \n");
	puts("#This program is free software; you can redistribute it and/or                             \n");
	*(char *)0x80000000='a';
	puts("#modify it under the terms of the GNU General Public License as                            \n");
	*(char *)0x80000000='a';
	puts("#published by the Free Software Foundation; either version 2 of                            \n");
	*(char *)0x80000000='a';
	*(char *)0x80000000='a';
	puts("#the License, or (at your option) any later version.                                       \n");
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("#This program is distributed in the hope that it will be useful,                           \n");
	*(char *)0x80000000='a';
	puts("#but WITHOUT ANY WARRANTY; without even the implied warranty of                            \n");
	*(char *)0x80000000='a';
	puts("#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the                           \n");
	*(char *)0x80000000='a';
	*(char *)0x80000000='a';
	puts("#GNU General Public License for more details.                                              \n");
	puts("#F                                                                                         \n");
	*(char *)0x80000000='a';
	puts("#You should have received a copy of the GNU General Public License                         \n");
	*(char *)0x80000000='a';
	puts("#along with this program; if not, write to the Free Software                               \n");
	*(char *)0x80000000='a';
	puts("#Foundation, Inc., 59 Temple Place, Suite 330, Boston,                                     \n");
	*(char *)0x80000000='a';
	puts("#MA 02111-1307 USA                                                                         \n");
	*(char *)0x80000000='a';
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("                                                                                            \n");
	*(char *)0x80000000='a';
	puts("Summary:                                                                                    \n");
	*(char *)0x80000000='a';
	puts("========                                                                                    \n");
	*(char *)0x80000000='a';
	puts("                                                                                            \n");
	*(char *)0x80000000='a';
	puts("This directory contains the source code for U-Boot, a boot loader for                       \n");
	*(char *)0x80000000='a';
	puts("Embedded boards based on PowerPC, ARM, MIPS and several other                               \n");
	*(char *)0x80000000='a';
	puts("processors, which can be installed in a boot ROM and used to                                \n");
	*(char *)0x80000000='a';
	puts("initialize and test the hardware or to download and run application                         \n");
	*(char *)0x80000000='a';
	puts("code.                                                                                       \n");
	*(char *)0x80000000='a';
	puts("                                                                                            \n");
	*(char *)0x80000000='a';
	testcopy();
	puts("The development of U-Boot is closely related to Linux: some parts of                        \n");
	puts("the source code originate in the Linux source tree, we have some                            \n");
	puts("header files in common, and special provision has been made to                              \n");
	puts("support booting of Linux images.                                                            \n");
	puts("                                                                                            \n");
	puts("Some attention has been paid to make this software easily                                   \n");
	puts("configurable and extendable. For instance, all monitor commands are                         \n");
	puts("implemented with the same call interface, so that it's very easy to                         \n");
	puts("add new commands. Also, instead of permanently adding rarely used                           \n");
	puts("code (for instance hardware test utilities) to the monitor, you can                         \n");
	puts("load and run it dynamically.                                                                \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Status:                                                                                     \n");
	puts("=======                                                                                     \n");
	puts("                                                                                            \n");
	testcopy32();
	puts("In general, all boards for which a configuration option exists in the                       \n");
	puts("Makefile have been tested to some extent and can be considered                              \n");
	puts("\"working\". In fact, many of them are used in production systems.                            \n");
	puts("                                                                                            \n");
	puts("In case of problems see the CHANGELOG and CREDITS files to find out                         \n");
	puts("who contributed the specific port.                                                          \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Where to get help:                                                                          \n");
	puts("==================                                                                          \n");
	puts("                                                                                            \n");
	puts("In case you have questions about, problems with or contributions for                        \n");
	puts("U-Boot you should send a message to the U-Boot mailing list at                              \n");
	puts("<u-boot-users@lists.sourceforge.net>. There is also an archive of                           \n");
	puts("previous traffic on the mailing list - please search the archive                            \n");
	testcopy();
	puts("before asking FAQ's. Please see                                                             \n");
	puts("http://lists.sourceforge.net/lists/listinfo/u-boot-users/                                   \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Where we come from:                                                                         \n");
	puts("===================                                                                         \n");
	puts("                                                                                            \n");
	puts("- start from 8xxrom sources                                                                 \n");
	puts("- create PPCBoot project (http://sourceforge.net/projects/ppcboot)                          \n");
	puts("- clean up code                                                                             \n");
	puts("- make it easier to add custom boards                                                       \n");
	puts("- make it possible to add other [PowerPC] CPUs                                              \n");
	puts("- extend functions, especially:                                                             \n");
	puts("  * Provide extended interface to Linux boot loader                                         \n");
	puts("  * S-Record download                                                                       \n");
	puts("  * network boot                                                                            \n");
	puts("  * PCMCIA / CompactFLash / ATA disk / SCSI ... boot                                        \n");
	puts("- create ARMBoot project (http://sourceforge.net/projects/armboot)                          \n");
	puts("- add other CPU families (starting with ARM)                                                \n");
	puts("- create U-Boot project (http://sourceforge.net/projects/u-boot)                            \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Names and Spelling:                                                                         \n");
	puts("===================                                                                         \n");
	puts("                                                                                            \n");
	puts("The \"official\" name of this project is \"Das U-Boot\". The spelling                           \n");
	puts("\"U-Boot\" shall be used in all written text (documentation, comments                         \n");
	puts("in source files etc.). Example:                                                             \n");
	puts("                                                                                            \n");
	puts("	This is the README file for the U-Boot project.                                           \n");
	puts("                                                                                            \n");
	puts("File names etc. shall be based on the string \"u-boot\". Examples:                            \n");
	puts("                                                                                            \n");
	puts("	include/asm-ppc/u-boot.h                                                                  \n");
	puts("                                                                                            \n");
	puts("	#include <asm/u-boot.h>                                                                   \n");
	puts("                                                                                            \n");
	puts("Variable names, preprocessor constants etc. shall be either based on                        \n");
	puts("the string \"u_boot\" or on \"U_BOOT\". Example:                                                \n");
	puts("                                                                                            \n");
	puts("	U_BOOT_VERSION		u_boot_logo                                                           \n");
	puts("	IH_OS_U_BOOT		u_boot_hush_start                                                     \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Versioning:                                                                                 \n");
	puts("===========                                                                                 \n");
	puts("                                                                                            \n");
	puts("U-Boot uses a 3 level version number containing a version, a                                \n");
	puts("sub-version, and a patchlevel: \"U-Boot-2.34.5\" means version \"2\",                           \n");
	puts("sub-version \"34\", and patchlevel \"4\".                                                       \n");
	puts("                                                                                            \n");
	puts("The patchlevel is used to indicate certain stages of development                            \n");
	puts("between released versions, i. e. officially released versions of                            \n");
	puts("U-Boot will always have a patchlevel of \"0\".                                                \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Directory Hierarchy:                                                                        \n");
	puts("====================                                                                        \n");
	puts("                                                                                            \n");
	puts("- board		Board dependent files                                                         \n");
	puts("- common	Misc architecture independent functions                                           \n");
	puts("- cpu		CPU specific files                                                                \n");
	puts("  - 74xx_7xx	Files specific to Freescale MPC74xx and 7xx CPUs                              \n");
	puts("  - arm720t	Files specific to ARM 720 CPUs                                                \n");
	puts("  - arm920t	Files specific to ARM 920 CPUs                                                \n");
	puts("    - at91rm9200 Files specific to Atmel AT91RM9200 CPU                                     \n");
	puts("    - imx	Files specific to Freescale MC9328 i.MX CPUs                                      \n");
	puts("    - s3c24x0	Files specific to Samsung S3C24X0 CPUs                                        \n");
	puts("  - arm925t	Files specific to ARM 925 CPUs                                                \n");
	puts("  - arm926ejs	Files specific to ARM 926 CPUs                                                \n");
	puts("  - arm1136	Files specific to ARM 1136 CPUs                                               \n");
	puts("  - i386	Files specific to i386 CPUs                                                       \n");
	puts("  - ixp		Files specific to Intel XScale IXP CPUs                                       \n");
	puts("  - mcf52x2	Files specific to Freescale ColdFire MCF52x2 CPUs                             \n");
	puts("  - mips	Files specific to MIPS CPUs                                                       \n");
	puts("  - mpc5xx	Files specific to Freescale MPC5xx  CPUs                                      \n");
	puts("  - mpc5xxx	Files specific to Freescale MPC5xxx CPUs                                      \n");
	puts("  - mpc8xx	Files specific to Freescale MPC8xx  CPUs                                      \n");
	puts("  - mpc8220	Files specific to Freescale MPC8220 CPUs                                      \n");
	puts("  - mpc824x	Files specific to Freescale MPC824x CPUs                                      \n");
	puts("  - mpc8260	Files specific to Freescale MPC8260 CPUs                                      \n");
	puts("  - mpc85xx	Files specific to Freescale MPC85xx CPUs                                      \n");
	puts("  - nios	Files specific to Altera NIOS CPUs                                                \n");
	puts("  - nios2	Files specific to Altera Nios-II CPUs                                             \n");
	puts("  - ppc4xx	Files specific to IBM PowerPC 4xx CPUs                                        \n");
	puts("  - pxa		Files specific to Intel XScale PXA CPUs                                       \n");
	puts("  - s3c44b0	Files specific to Samsung S3C44B0 CPUs                                        \n");
	puts("  - sa1100	Files specific to Intel StrongARM SA1100 CPUs                                 \n");
	puts("- disk		Code for disk drive partition handling                                        \n");
	puts("- doc		Documentation (don't expect too much)                                             \n");
	puts("- drivers	Commonly used device drivers                                                      \n");
	puts("- dtt		Digital Thermometer and Thermostat drivers                                        \n");
	puts("- examples	Example code for standalone applications, etc.                                \n");
	puts("- include	Header Files                                                                      \n");
	puts("- lib_arm	Files generic to ARM	 architecture                                             \n");
	puts("- lib_generic	Files generic to all	 architectures                                        \n");
	puts("- lib_i386	Files generic to i386	 architecture                                         \n");
	puts("- lib_m68k	Files generic to m68k	 architecture                                         \n");
	puts("- lib_mips	Files generic to MIPS	 architecture                                         \n");
	puts("- lib_nios	Files generic to NIOS	 architecture                                         \n");
	puts("- lib_ppc	Files generic to PowerPC architecture                                             \n");
	puts("- net		Networking code                                                                   \n");
	puts("- post		Power On Self Test                                                            \n");
	puts("- rtc		Real Time Clock drivers                                                           \n");
	puts("- tools		Tools to build S-Record or U-Boot images, etc.                                \n");
	puts("                                                                                            \n");
	puts("Software Configuration:                                                                     \n");
	puts("=======================                                                                     \n");
	puts("                                                                                            \n");
	puts("Configuration is usually done using C preprocessor defines; the                             \n");
	puts("rationale behind that is to avoid dead code whenever possible.                              \n");
	puts("                                                                                            \n");
	puts("There are two classes of configuration variables:                                           \n");
	puts("                                                                                            \n");
	puts("* Configuration _OPTIONS_:                                                                  \n");
	puts("  These are selectable by the user and have names beginning with                            \n");
	puts("  \"CONFIG_\".                                                                                \n");
	puts("                                                                                            \n");
	puts("* Configuration _SETTINGS_:                                                                 \n");
	puts("  These depend on the hardware etc. and should not be meddled with if                       \n");
	puts("  you don't know what you're doing; they have names beginning with                          \n");
	puts("  \"CFG_\".                                                                                   \n");
	puts("                                                                                            \n");
	puts("Later we will add a configuration tool - probably similar to or even                        \n");
	puts("identical to what's used for the Linux kernel. Right now, we have to                        \n");
	puts("do the configuration by hand, which means creating some symbolic                            \n");
	puts("links and editing some configuration files. We use the TQM8xxL boards                       \n");
	puts("as an example here.                                                                         \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Selection of Processor Architecture and Board Type:                                         \n");
	puts("---------------------------------------------------                                         \n");
	puts("                                                                                            \n");
	puts("For all supported boards there are ready-to-use default                                     \n");
	puts("configurations available; just type \"make <board_name>_config\".                             \n");
	puts("                                                                                            \n");
	puts("Example: For a TQM823L module type:                                                         \n");
	puts("                                                                                            \n");
	puts("	cd u-boot                                                                                 \n");
	puts("	make TQM823L_config                                                                       \n");
	puts("                                                                                            \n");
	puts("For the Cogent platform, you need to specify the cpu type as well;                          \n");
	puts("e.g. \"make cogent_mpc8xx_config\". And also configure the cogent                             \n");
	puts("directory according to the instructions in cogent/README.                                   \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Configuration Options:                                                                      \n");
	puts("----------------------                                                                      \n");
	puts("                                                                                            \n");
	puts("Configuration depends on the combination of board and CPU type; all                         \n");
	puts("such information is kept in a configuration file                                            \n");
	puts("\"include/configs/<board_name>.h\".                                                           \n");
	puts("                                                                                            \n");
	puts("Example: For a TQM823L module, all configuration settings are in                            \n");
	puts("\"include/configs/TQM823L.h\".                                                                \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("Many of the options are named exactly as the corresponding Linux                            \n");
	puts("kernel configuration options. The intention is to make it easier to                         \n");
	puts("build a config tool - later.                                                                \n");
	puts("                                                                                            \n");
	puts("                                                                                            \n");
	puts("The following options need to be configured:                                                \n");
	puts("                                                                                            \n");
	puts("- CPU Type:	Define exactly one of                                                         \n");
	puts("                                                                                            \n");
	puts("		PowerPC based CPUs:                                                                   \n");
	puts("		-------------------                                                                   \n");
	puts("		CONFIG_MPC823,	CONFIG_MPC850,	CONFIG_MPC855,	CONFIG_MPC860                         \n");
	puts("	or	CONFIG_MPC5xx                                                                         \n");
	puts("	or	CONFIG_MPC8220                                                                        \n");
	puts("	or	CONFIG_MPC824X, CONFIG_MPC8260                                                        \n");
	puts("	or	CONFIG_MPC85xx                                                                        \n");
	puts("	or	CONFIG_IOP480                                                                         \n");
	puts("	or	CONFIG_405GP                                                                          \n");
	puts("	or	CONFIG_405EP                                                                          \n");
	puts("	or	CONFIG_440                                                                            \n");
	puts("	or	CONFIG_MPC74xx                                                                        \n");
	puts("	or	CONFIG_750FX                                                                          \n");
	puts("                                                                                            \n");
	puts("		ARM based CPUs:                                                                       \n");
	puts("		---------------                                                                       \n");

}
void testuart1()
{
	unsigned int i;
	puts("------------------begin uart test 1----------------- \n");
	puts("------------------begin uart test 1----------------- \n");
	puts("------------------begin uart test 1----------------- \n");
	puts("------------------begin uart test 1----------------- \n");
	puts("------------------begin uart test 1----------------- \n");
	puts("------------------begin uart test 1----------------- \n");
	
	puts("# (C) Copyright 2001 - 2005                                                                 \n");  
	puts("# Wolfgang Denk, DENX Software Engineering, wd@denx.de.                                     \n");
	*(char *)0x80000000='a';

	puts("#                                                                                           \n");
	puts("# See file CREDITS for list of people who contributed to this                               \n");
	puts("# project.                                                                                  \n");
	*(char *)0x80000000='a';
	puts("#                                                                                           \n");
	puts("# This program is free software; you can redistribute it and/or                             \n");
	*(char *)0x80000000='a';
	puts("# modify it under the terms of the GNU General Public License as                            \n");
	*(char *)0x80000000='a';
	puts("# published by the Free Software Foundation; either version 2 of                            \n");
	*(char *)0x80000000='a';
	*(char *)0x80000000='a';
	puts("# the License, or (at your option) any later version.                                       \n");
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("# This program is distributed in the hope that it will be useful,                           \n");
	*(char *)0x80000000='a';
	puts("# but WITHOUT ANY WARRANTY; without even the implied warranty of                            \n");
	*(char *)0x80000000='a';
	puts("# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the                           \n");
	*(char *)0x80000000='a';
	*(char *)0x80000000='a';
	puts("# GNU General Public License for more details.                                              \n");
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("# You should have received a copy of the GNU General Public License                         \n");
	*(char *)0x80000000='a';
	puts("# along with this program; if not, write to the Free Software                               \n");
	*(char *)0x80000000='a';
	puts("# Foundation, Inc., 59 Temple Place, Suite 330, Boston,                                     \n");
	*(char *)0x80000000='a';
	puts("# MA 02111-1307 USA                                                                         \n");
	*(char *)0x80000000='a';
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("                                                                                            \n");
	*(char *)0x80000000='a';
	puts("Summary:                                                                                    \n");
	*(char *)0x80000000='a';
	puts("========                                                                                    \n");
	*(char *)0x80000000='a';
	puts("                                                                                            \n");
	*(char *)0x80000000='a';
	puts("This directory contains the source code for U-Boot, a boot loader for                       \n");
	*(char *)0x80000000='a';
	puts("Embedded boards based on PowerPC, ARM, MIPS and several other                               \n");
	*(char *)0x80000000='a';
}
void testuart2()
{
	unsigned int i;
	puts("------------------begin uart test 2----------------- \n");
	puts("------------------begin uart test 2----------------- \n");
	puts("------------------begin uart test 2----------------- \n");
	puts("------------------begin uart test 2----------------- \n");
	puts("------------------begin uart test 2----------------- \n");
	
	puts("# (C) Copyright 2001 - 2005                                                                 \n");  
	puts("# Wolfgang Denk, DENX Software Engineering, wd@denx.de.                                     \n");
	*(char *)0x80000000='a';

	puts("#                                                                                           \n");
	puts("# See file CREDITS for list of people who contributed to this                               \n");
	puts("# project.                                                                                  \n");
	*(char *)0x80000000='a';
	puts("#                                                                                           \n");
	puts("# This program is free software; you can redistribute it and/or                             \n");
	*(char *)0x80000000='a';
	puts("# modify it under the terms of the GNU General Public License as                            \n");
	*(char *)0x80000000='a';
	testcopy();
	puts("# published by the Free Software Foundation; either version 2 of                            \n");
	*(char *)0x80000000='a';
		
	*(char *)0x80000000='a';
	puts("# the License, or (at your option) any later version.                                       \n");
	puts("#                                                                                           \n");
	*(char *)0x80000000='a';
	puts("# This program is distributed in the hope that it will be useful,                           \n");
}
#endif
