#!/bin/sh

if make f23pv1e
then
	if make
	then
		if make install
		then
			echo "====================="
			echo "======= Done ========"
			echo "====================="
			cp build/opvos.bin /tftpboot/
			echo ""
			echo "=== cp build/opvos.bin /tftpboot/  !!==="
		else
			echo "====================="
			echo "======= Error ======="
			echo "====================="
		fi
	else
			echo "====================="
			echo "======= Error ======="
			echo "====================="
	fi
else
	echo "====================="
	echo "======= Error ======="
	echo "====================="
fi
