#!/bin/sh

if make rf400gna
then
	if make
	then
		if make install
		then
			echo "====================="
			echo "======= Done ========"
			echo "====================="
		else
			echo "====================="
			echo "======= Error ======="
			echo "====================="
		fi
	else
			echo "====================="
			echo "======= Error ======="
			echo "====================="
	fi
else
	echo "====================="
	echo "======= Error ======="
	echo "====================="
fi
