

obj-y += irq.o cmdline.o puts_new.o time.o

obj-$(CONFIG_KGDB_OPTRANN_SERIAL)  += kgdb_serial.o


#obj-$(CONFIG_ONU_EVA_BOARD)  += setup.o platfrom.o
obj-$(CONFIG_ONU_D2_F33_BOARD)  += setup.o platform_d2_f33.o
obj-$(CONFIG_ONU_F23_BOARD)  += setup.o platform_f23.o
obj-$(CONFIG_ONU_F13_BOARD)  += setup.o platform_f13.o
obj-$(CONFIG_ONU_F13S_VOIP_BOARD)  += setup.o platform_voip_f13s.o
obj-$(CONFIG_ONU_F13P_VOIP_BOARD)  += setup.o platform_voip_f13p.o
obj-$(CONFIG_ONU_F23P_VOIP_BOARD)  += setup.o platform_voip_f23p.o
obj-$(CONFIG_ONU_F23S_VOIP_BOARD)  += setup.o platform_voip_f23s.o
obj-$(CONFIG_ONU_F23S_VOIP_UT_BOARD)  += setup_ut.o platform_voip_f23s_ut.o
obj-$(CONFIG_ONU_F33_VOIP_BOARD)   += setup.o platform_voip_f33.o
obj-$(CONFIG_ONU_C13_BOARD)  += setup.o platform_c13.o
obj-$(CONFIG_ONU_F13P_VOIP_PCM_WDT_BOARD)  += setup.o platform_voip_f13p.o
obj-$(CONFIG_ONU_RESPIN_C13_BOARD)  += setup.o platform_onu_respin_c13.o
obj-$(CONFIG_ONU_RESPIN_F13_BOARD)  += setup.o platform_onu_respin_f13.o
obj-$(CONFIG_ONU_RESPIN_F23_BOARD)  += setup.o platform_onu_respin_f23.o
obj-$(CONFIG_ONU_RESPIN_C13_SPI_BOARD)  += setup.o platform_onu_respin_c13_spi.o
obj-$(CONFIG_ONU_RESPIN_C13_SPI_300M_BOARD)  += setup.o platform_onu_respin_c13_spi_300m.o
obj-$(CONFIG_ONU_RESPIN_RF400_BOARD)  += setup.o platform_onu_respin_rf400.o
obj-$(CONFIG_ONU_RESPIN_RF400P_BOARD)  += setup.o platform_onu_respin_rf400p.o
obj-$(CONFIG_ONU_RESPIN_F23P_BOARD)  += setup.o platform_onu_respin_f23p.o

