#MODULE_DIR := /home/hxu/work/linux-module/opl_linux_module_my
PWD := $(shell /bin/pwd)

module-objs = opl_cs1_mmap.o
obj-m= opl_cs1_mmap.o
MODULE_NAME = opl_cs1_mmap.ko

include $(MODULE_DIR)/build/Makefile.conf


