#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2009 Opulan Technology

obj-$(CONFIG_ARCH_OPTRANN) += optrann/
obj-$(CONFIG_ARCH_ONU) += onu/
obj-$(CONFIG_ARCH_ONU2) += onu2/

